[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  headers = {X-Form = "Netlify"}

[[redirects]]
  from = "/api/*"
  to = "https://paaumarketserver.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {X-Form = "Netlify"}

[[redirects]]
  from = "/storage/images/*"
  to = "https://paaumarketserver.onrender.com/storage/images/:splat"
  status = 200
  force = true
  headers = {X-Form = "Netlify"}